# Generated by Django 5.1.3 on 2024-11-07 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyThreatCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
