# Generated by Django 5.1.3 on 2024-11-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0002_dailythreatcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLeakCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
