# Generated by Django 5.1.3 on 2024-11-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0003_monthlyleakcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyleakcount',
            name='count',
            field=models.IntegerField(),
        ),
    ]
